

# This file was *autogenerated* from the file nrands_est.sage
from sage.all_cmdline import *   # import sage library

_sage_const_60 = Integer(60); _sage_const_8730 = Integer(8730); _sage_const_1p = RealNumber('1.'); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_10 = Integer(10); _sage_const_140 = Integer(140); _sage_const_2 = Integer(2); _sage_const_1p025 = RealNumber('1.025'); _sage_const_1 = Integer(1)
from batchCVP import batchCVPP_cost
from sage.plot.scatter_plot import ScatterPlot

dim = _sage_const_60 

cdb_size = (_sage_const_8730 )**(_sage_const_1p /dim)
print("cdb_size:", cdb_size, sqrt(_sage_const_4 /_sage_const_3 ).n())


data = []
for M in range(_sage_const_10 , _sage_const_140 , _sage_const_10 ):
    log_M = log(M, _sage_const_2 ).n()
    prob, T = batchCVPP_cost(dim, log_M, cdb_size, _sage_const_1p025 ) #change sqrt(4/3) to the value cdb_size()^{1/dim}
    data.append([M,min(_sage_const_1 ,(prob**dim)*M)])

print(data)


g = Graphics()
g+= list_plot(data, marker='+', color='darkgreen')
g.show()
g.save("nrands_"+str(dim)+".png")

