

# This file was *autogenerated* from the file runtime.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_1p = RealNumber('1.'); _sage_const_2p = RealNumber('2.'); _sage_const_3 = Integer(3); _sage_const_1p1 = RealNumber('1.1'); _sage_const_1p9 = RealNumber('1.9')
var('a')
T1 = ((a - _sage_const_2 *(a-_sage_const_1 )/(_sage_const_1 +sqrt(_sage_const_1 -_sage_const_1p /a)))**(-_sage_const_1 /_sage_const_2p ))*a
T2 = _sage_const_1p /(a*(_sage_const_1 +_sage_const_2 *(_sage_const_1 -_sage_const_1 /a)**(_sage_const_3 /_sage_const_2 )-_sage_const_3 *(_sage_const_1 -_sage_const_1p /a)))

g = Graphics()
g += plot(T1, a, [_sage_const_1p1 , _sage_const_1p9 ], color="red")
g += plot(T2, a, [_sage_const_1p1 , _sage_const_1p9 ], color="blue")
g.show()

